### PR TITLE
Making Description Field URL-aware

### PR DESCRIPTION
**Pull request by gavinr**
Added regex to detect URLs (that begin with http://) (credit: http://stackoverflow.com/a/37687), and disabled auto-escaping in the dust template to allow these urls to show up on the page.

### CODE REVIEW

**Comment by automatonic** [comment]
Will try and address this tonight

**Comment by gavinr** [comment]
Great! Here is my test page, in case it helps you out (although I'm sure you'll want to run your own series of tests) http://gavhost.com/cal/

**Comment by automatonic** [comment]
Cool. Thanks for the contrib. I have jasmine framework set up in v1.0 branch, and will try to get some unit tests worked in through that.

**Comment by automatonic** [comment]
So, i spent a bunch of time making things more testable, should be to your change shortly. Unfortunately the merge is "whole file" (for my v0.1 branch), so looks like i will just be manually integrating. Further, i have a scheme to inject the link tags without turning off other relevant escaping (html, javascript, etc. that might be maliciously in the event data). Rest assured that I will be basing my solution on your suggestion though.

**Comment by gavinr** [comment]
Works for me. Thanks!

**Pull request closed without merging**
